Fix memory leaks in PeerConnection
node-webrtc/node-webrtc pull request #426
Opened 2018-08-30 21:52 UTC by sebas642

* CreateOffer
  * CreateAnswer
  * AddIceCandidate
  * GetStats

Fixes #425

2018-08-30 23:01 UTC, markandrus requested changes
Thanks a lot for these changes! The build is failing due to this:

```
You must run make format before submitting a pull request
diff --git a/src/peerconnection.cc b/src/peerconnection.cc
index 55214a7..ac7b596 100644
--- a/src/peerconnection.cc
+++ b/src/peerconnection.cc
@@ -522,7 +522,7 @@ NAN_METHOD(PeerConnection::GetStats) {
   if (self->_jinglePeerConnection != nullptr) {
     auto statsObserver = new rtc::RefCountedObject<StatsObserver>(self, std::move(promise));
     if (!self->_jinglePeerConnection->GetStats(statsObserver, nullptr,
-        webrtc::PeerConnectionInterface::kStatsOutputLevelStandard)) {
+            webrtc::PeerConnectionInterface::kStatsOutputLevelStandard)) {
       auto error = Nan::Error("Failed to execute getStats");
       resolver->Reject(error);
     }
```

Can you run `make format` (or edit manually) and update the PR?

2018-08-30 23:01 UTC, markandrus commented on src/peerconnection.cc
> +  delete candidate;
Nice 👍

2018-08-30 23:01 UTC, markandrus commented on src/createsessiondescriptionobserver.cc
> +  delete sdp;
Didn't realize this was a part of the contract! 👍I checked [the WebRTC source](https://chromium.googlesource.com/external/webrtc/stable/talk/+/master/app/webrtc/jsep.h) and can confirm:

```c++
// The implementation of the CreateSessionDescriptionObserver takes
// the ownership of the \|desc\|.
virtual void OnSuccess(SessionDescriptionInterface* desc) = 0;
```

2018-08-31 16:56 UTC, sebas642 commented
I have fixed the formatting. Sorry about that!

2018-08-31 17:51 UTC, markandrus approved these changes

2018-08-31 17:52 UTC, merged

2018-08-31 17:52 UTC, markandrus commented
Thanks! 🎉